spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-user
    password: '{cipher}3adfb46bde0f96695af1853733d8774f0012b158e34b64a1254660f509c65e1b666020c71b435e7a78a36d31c2845cbf'
  datasource:
    url: jdbc:mysql://localhost:3307/chat_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: chat-service-user
    password: '{cipher}51aad89a42a95e5bba0c4ca0b69a47a47cc19ddd4705418b63f5b8dac31fb4f2ee7194e556b0c154cb5e059fa2047ded'
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 9997
  forward-headers-strategy: framework
logging:
  level:
    pl:
      kubaretip:
        chatservice: debug