spring:    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: false
    fetch-registry: true
    enabled: true
